# Generated by Django 5.1 on 2024-09-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karjoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('grades', models.CharField(max_length=20)),
                ('work_filed', models.CharField(max_length=20)),
                ('work_experience', models.CharField(max_length=20)),
                ('karjoo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='karjoo.karjoo')),
            ],
        ),
    ]
