# Generated by Django 5.1 on 2024-09-11 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karfarma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karjoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('karjoo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='karjoo.karjoo')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='karfarma.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('grades', models.CharField(choices=[('HS', 'High School'), ('BA', 'Bachelors'), ('MA', 'Masters'), ('PhD', 'Doctorate')], max_length=20)),
                ('work_filed', models.CharField(max_length=20)),
                ('work_experience', models.CharField(max_length=20)),
                ('karjoo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='karjoo.karjoo')),
            ],
        ),
    ]
